PROMPT='%m:$FG[004]%2d$(git_prompt_info)$(git_prompt_ahead)$FG[013]$(virtualenv_prompt_info)%{$reset_color%} > '

ZSH_THEME_GIT_PROMPT_PREFIX="$FG[244]:$FG[011]"
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY=" $FG[009]𝚫"
ZSH_THEME_GIT_PROMPT_AHEAD=" $FG[009]↗"
ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_VIRTUALENV_PREFIX=" "
ZSH_THEME_VIRTUALENV_SUFFIX=""
